import Head from 'next/head'
import PageIndex from "@/components/PageIndex/PageIndex";


export default function Home() {
  return (
    <>
      <Head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PageIndex />
      </main>
    </>
  )
}
