import Head from 'next/head'
import PageSecond from "@/components/PageSecond/PageSecond";

export default function secondPage() {
    return (
        <>
            <Head>
                <title>Second page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <PageSecond />
            </main>
        </>
    )
}
